### PR TITLE
feat: report status of the spec closes #129

### LINKED ISSUE #129: Expose 'disabled' and 'pending' statuses to let reporter differentiate them
Jasmine exposes `'disabled'` and `'pending'` statuses via [specResult.status](https://github.com/jasmine/jasmine/blob/v2.4.1/lib/jasmine-core/jasmine.js#L411).

IIUC, `specResult.disabled === true` means that there is at least one [focused spec](http://jasmine.github.io/2.4/focused_specs.html) (`fdescribe/fit`) and this spec is not declared as focused.

`specResult.pending === true` means that this spec is declared as [pending](http://jasmine.github.io/2.4/introduction.html#section-Pending_Specs) (`xdescribe/xit` or without a function body).

Currently, karma-jasmine merges both these statuses into `skipped` (https://github.com/karma-runner/karma-jasmine/blob/v1.0.2/src/adapter.js#L214) making it impossible for a reporter to handle these statuses differently. E.g. for IDE reporter, it would be convenient to show pending specs in a result test tree conditionally (e.g. if "Show Pending" is enabled) and hide disabled spec always.

Would be great if a reporter could access `result.disabled` and `result.pending` values in [`onSpecComplete(browser, result)`](https://github.com/karma-runner/karma/blob/v1.1.2/lib/reporters/base.js#L79).
Thanks!

### PR DESCRIPTION
**Pull request by maksimr**
cc @segrey @dignifiedquire

### CODE REVIEW

**Comment by dignifiedquire** [comment]
Looks good to me, @segrey please let us know if this works for you

**Comment by segrey** [comment]
This works for me as well. Maybe just a small improvement: let's rename `result.status` property to `result.jasmineStatus` to indicate that this property is exposed directly from jasmine (thus jasmine docs should be consulted to clarify the details) and other adapters won't have it.
[Offtopic] how about introducing `disabled` and `pending` statuses on karma level API? That would make it test framework agnostic simplifying reporter's life :). E.g. mocha adapter could also provide these statuses I guess.

**Comment by maksimr** [comment]
@segrey does mocha have statuses 'disabled' and 'pending'?

**Comment by segrey** [comment]
@maksimr ah, it turned out that things are different for mocha. Mocha has [pending tests](http://mochajs.org/#pending-tests) which have `test.pending` status and are reported as `result.skipped` (https://github.com/karma-runner/karma-mocha/blob/v1.1.1/src/adapter.js#L110). However, mocha doesn't report tests with `'disabled'` status, which are all tests other than [exclusive](http://mochajs.org/#exclusive-tests). Thus, one can say that mocha has `disabled` status, but it just doesn't report it :)
Since karma-intellij [silently ignores](https://github.com/karma-runner/karma-intellij/blob/master/lib/intellijReporter.js#L220) all skipped tests then currently pending mocha tests are not shown in a result test tree. Will file a separate issue in https://github.com/karma-runner/karma-mocha/ regarding reporting pending status for mocha tests.

**Comment by segrey** [comment]
As for the introduced `result.status`, taking into account its general name, not sure I understand in which way `result.status` should be treated by a reporter:
* It is an internal jasmine status which can be changed in a subsequent jasmine release. Reporter may use it at its own risk. Also, `result.status` is defined for karma-adapter only. In this case, `result.jasmineStatus` suites better.
* It is a part of karma API and `result.status` values are unified between different adapters. If a test framework changes it's internal status format (e.g. for jasmine, `specResult.status` may be changed to `'skipped'` instead of `'disabled'`), a corresponding adapter is updated and unchanged `result.status` values is maintained.

**Comment by segrey** [comment]
>Will file a separate issue in https://github.com/karma-runner/karma-mocha/ regarding reporting pending status for mocha tests.

Done https://github.com/karma-runner/karma-mocha/issues/109

**Comment by maksimr** [comment]
@segrey I have updated changes, check plz

**Comment by segrey** [comment]
@maksimr LGTM, thank you

**Pull request merged**
