### PR TITLE
docs(README.md): minor grammar fixes

### PR DESCRIPTION
**Pull request by Aaron-Hartwig**

### CODE REVIEW

**Comment by maksimr** [comment]
@Aaron-Hartwig Thanks!

Change please commit message following [commit message convention](http://karma-runner.github.io/0.12/dev/git-commit-msg.html)

**Comment by Aaron-Hartwig** [comment]
@maksimr is this better?

**Comment by maksimr** [comment]
@Aaron-Hartwig Awesome! Thanks

**Comment by stevemao** [comment]
Only title is changed. Not the commit message.

**Pull request merged**
