### PR TITLE
chore(npm): select lib files rather than ignore random files

### PR DESCRIPTION
**Pull request by johnjbarton**

### CODE REVIEW

**Comment by XhmikosR** [comment]
```

C:\Users\xmr\Desktop\karma-jasmine>npm pack --dry
npm notice
npm notice package: karma-jasmine@3.1.0
npm notice === Tarball Contents ===
npm notice 1.1kB  LICENSE
npm notice 15.6kB lib/adapter.js
npm notice 1.4kB  lib/boot.js
npm notice 65B    commitlint.config.js
npm notice 743B   spec/index_spec.js
npm notice 968B   lib/index.js
npm notice 435B   release.config.js
npm notice 446B   wallaby.js
npm notice 181B   spec/support/jasmine.json
npm notice 3.4kB  package.json
npm notice 12.1kB CHANGELOG.md
npm notice 2.7kB  README.md
npm notice === Tarball Details ===
npm notice name:          karma-jasmine
npm notice version:       3.1.0
npm notice filename:      karma-jasmine-3.1.0.tgz
npm notice package size:  11.3 kB
npm notice unpacked size: 39.2 kB
npm notice shasum:        2e342518a04505f2105847d2c9fb27d315c4e452
npm notice integrity:     sha512-kLs1NW0Jbdjuu[...]przsG6wnYLcLg==
npm notice total files:   12
npm notice
karma-jasmine-3.1.0.tgz
```

vs this patch:

```

C:\Users\xmr\Desktop\karma-jasmine>npm pack --dry
npm notice
npm notice package: karma-jasmine@3.1.0
npm notice === Tarball Contents ===
npm notice 1.1kB  LICENSE
npm notice 15.6kB lib/adapter.js
npm notice 1.4kB  lib/boot.js
npm notice 968B   lib/index.js
npm notice 3.5kB  package.json
npm notice 12.1kB CHANGELOG.md
npm notice 2.7kB  README.md
npm notice === Tarball Details ===
npm notice name:          karma-jasmine
npm notice version:       3.1.0
npm notice filename:      karma-jasmine-3.1.0.tgz
npm notice package size:  10.6 kB
npm notice unpacked size: 37.4 kB
npm notice shasum:        0d40bf22f4f940a1669dc26a7ecb3269e3c56d34
npm notice integrity:     sha512-BmXQFmfYsPVQA[...]LDrAdSnFZxLGg==
npm notice total files:   7
npm notice
karma-jasmine-3.1.0.tgz
```

Does it look OK?

PS. @johnjbarton probably better to make upstream branches and wait for feedback when you ask for it :P

**Comment by johnjbarton** [comment]
> PS. @johnjbarton probably better to make upstream branches and wait for feedback when you ask for it :P

Could you expand on what you mean here?  From my side I saw you approve the PR so I merged.

**Comment by XhmikosR** [comment]
I didn't approve it :) I just fixed it and I was still testing things out.

**Comment by johnjbarton** [comment]
> Does it look OK?

Yes (though I think "lib" would also  work)

**Comment by johnjbarton** [comment]
Maybe the UI from github is not great. As admin everything seems green all of the time ;-)

**Comment by XhmikosR** [comment]
>Yes (though I think "lib" would also work)

Yeah, but it's too lax IMO. Better be stricter

**Pull request merged**
