### PR TITLE
chore: minor README.md tweaks

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by XhmikosR** [comment]
I'm not familiar with conventional commit messages, so just let me know what to use

**Comment by johnjbarton** [comment]
the new husky/commitlint should be running so if they pass it should be ok.  I just usually prefer the domain-scoped titles.  kind(scope): what-changed.

**Comment by XhmikosR** [comment]
@johnjbarton one last thing: can you enable the `delete HEAD branches` in all karma repositories? Now the merged branches are left behind.

**Comment by johnjbarton** [comment]
done.  What do you think about removing "Allow merge commits"?

**Comment by XhmikosR** [comment]
Yeah, I don't use it either. Only squash and rebase, but it doesn't matter if you are consistent :)

**Pull request merged**
