### PR TITLE
Setup semantic-release

### PR DESCRIPTION
**Pull request by limonte**
Closes our emotional discussion in https://github.com/karma-runner/karma-jasmine/issues/242#issuecomment-572126898 :)

You're already using [Angular Commit Message Conventions]( https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#-git-commit-guidelines) for this repo, so setting up `semantic-release` is simple, read more: https://github.com/semantic-release/semantic-release/

In order to publish to GitHub, add `GH_TOKEN` or `GITHUB_TOKEN` env variable in Travis config, read more: https://github.com/semantic-release/github/#environment-variables

In order to publish to npm, add `NPM_TOKEN` env variable in Travis config, read more: https://github.com/semantic-release/npm#environment-variables

That should be it.

### CODE REVIEW

**Comment by limonte** [comment]
One detail to finish here, the `after_success` task should run only once. Currently, it's being triggered for every node_js version.

**Comment by limonte** [comment]
> 
> 
> Thanks! Let's give this a try. If it works well we can use it on other karma-runner/*

You're welcome! Sure, you can apply the same config for other repos. As you can see, the configuration is quite simple.

**Comment by limonte** [comment]
The [releasing process](https://travis-ci.org/karma-runner/karma-jasmine/jobs/634509512) failed because env variables aren't set, add `GH_TOKEN` and `NPM_TOKEN` to Travis and re-run the build, then the releasing magic should happen.

**Comment by johnjbarton** [comment]
Like #249 ?

**Comment by limonte** [comment]
> 
> 
> Like #249 ?

No. You just exposed your sensitive data, you need to delete those tokens ASAP!

**Comment by limonte** [comment]
The right way is described here: https://docs.travis-ci.com/user/environment-variables/#defining-variables-in-repository-settings

**Comment by johnjbarton** [comment]
Thanks, but our travis acct has no repo settings.  I'll have to dig in to that.

**Comment by johnjbarton** [comment]
ok eventually I got all the things to work. Thanks!

**Pull request merged**
