### PR TITLE
fix: v0.3.7 does not work in ie8 fix #105

### LINKED ISSUE #105: v0.3.7 does not work in ie8
Hi!

From `v0.3.7` you've added [some code](https://github.com/karma-runner/karma-jasmine/blob/v0.3.7/src/adapter.js#L264) which does not work in ie8 (`indexOf`).

### PR DESCRIPTION
**Pull request by maksimr**

### CODE REVIEW

**Comment by maksimr** [comment]
@dignifiedquire what do you think about these changes?

**Comment by dignifiedquire** [comment]
I'm not sure this is a good idea, if we shim globals and people start relying on them in their tests, things will suddenly fail in production. Maybe we just add a comment in the notes that for these browsers you should include an appropriate es5 shim? Or am I missing sth? Also if we pull this in I'd rather use a shim library rather than duplicating these here.

**Comment by maksimr** [comment]
@dignifiedquire yeh,

I taught about this but I decided to make fix because jasmine-core support IE8 and usage of filter and map in our code it's our problem and to force people use es5 shim only because karma-jasmine adapter use it's a "so so" solution.

**Comment by dignifiedquire** [comment]
How about we use the lodash methods instead? that way we do not do any polyfilling and we have explicit dependencies

**Comment by maksimr** [comment]
Do you want to load `lodash` [here](https://github.com/karma-runner/karma-jasmine/blob/master/lib/index.js#L10)?

**Comment by dignifiedquire** [comment]
Nvm, I'm too tired to say anything useful...

**Comment by maksimr** [comment]
@dignifiedquire  ok :)

**Comment by dignifiedquire** [comment]
Merging this for now as I don't have a better solution, thanks @maksimr

**Comment by maksimr** [comment]
@dignifiedquire no problem!

**Pull request merged**
