### PR TITLE
allow booting in a JS-only environment

### PR DESCRIPTION
**Pull request by tailsu**

### CODE REVIEW

**Comment by Dignifiedquire** [comment]
Hey thanks for the contribution. Could you please change the commit message to follow our [conventions](karma-runner.github.io/0.12/dev/git-commit-msg.html)

**Comment by maksimr** [comment]
@tailsu can you describe your case where you use karma-jasmine in non browser environment?

Thanks!

**Comment by tailsu** [comment]
I'm working on a prototype test runner for [NativeScript](https://github.com/nativescript/nativescript)-based apps. I'm already able to run jasmine-based tests in the NS runtime and report the results back. I just wish to remove all the dummy browserification code from the prototype, hence this commit.

What do you think? :)

**Comment by tailsu** [comment]
I'll fix the commit message tomorrow.

**Comment by Dignifiedquire** [comment]
> What do you think? :)

Sounds really cool, happy to support something like that with a one line fix

**Comment by maksimr** [comment]
@tailsu +1 sounds great!

I asked because if your environment does not contain `window` property then you will get error like:

```js
ReferenceError: window is not defined
```

More robust solution would be:

```js
(function(...){
  ...
}(typeof window !== 'undfined' ? window : global ));
```

**Comment by tailsu** [comment]
@maksimr You were right, I had forgotten to remove the `global.window = global`, because I thought something else depended on it. Removed that, tested, crashed with `ReferenceError`, applied fixes, tested again, works.

**Comment by maksimr** [comment]
LGTM

**Pull request merged**
