### PR TITLE
Adding timeout configuration option

### PR DESCRIPTION
**Pull request by fadc80**
Adding an option to change the default jasmine timeout interval globally.

### CODE REVIEW

**Comment by fadc80** [comment]
I signed it!

**Comment by fadc80** [comment]
I signed it!

**Comment by fadc80** [comment]
I explained my motivation for this PR on you [mailling list](https://groups.google.com/forum/#!topic/karma-users/qQBcY3OLk4M).

**Comment by fadc80** [comment]
When are you planing ti release a new version?

**Comment by aleshaanddustin18** [comment]
New version of what

**Comment by fadc80** [comment]
Karma-jasmine plugin

**Comment by dmk1111** [comment]
@johnjbarton @dignifiedquire @zzo 

Could you please respond with some estimations, when next release that will include this feature is planned?

Thank you!

**Comment by webmaster128** [comment]
Ahhh, I was trying to use this feature but it is not released yet – makes sense

**Comment by johnjbarton** [comment]
Now that karma 3.0 is out I plan a karma-jasmine release but it will deps jasmine 3.x and I have many tests on jasmine 2.x to migrate first.

**Comment by mariotacke** [comment]
Any news on this? Would love to use the `timeoutInterval`. The [README](https://github.com/karma-runner/karma-jasmine#readme) already has it as an option.

> If you want to pass configuration options directly to jasmine you can do this in the following way

```
module.exports = function(config) {
  config.set({
    client: {
      jasmine: {
        random: true,
        seed: '4321',
        stopOnFailure: true,
        failFast: true,
        timeoutInterval: 1000
      }
    }
  })
}
```

**Comment by webmaster128** [comment]
Works like a charm in the recent 2.x release.

**Pull request merged**
